# Generated by Django 5.2.7 on 2025-10-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('RENTED', 'Rented'), ('EXPIRED', 'Expired')], db_index=True, default='DRAFT', max_length=10),
        ),
    ]
